sonar.host.url=https://sonarcloud.io
sonar.organization=rolitoansu
sonar.projectKey=Rolitoansu_Match-TFE

# Definimos los módulos
sonar.modules=authservice,gatewayservice,notificationservice,projectservice,userservice,webapp

# --- Auth Service ---
authservice.sonar.projectName=Auth Service
authservice.sonar.sources=authservice.ts, validate.ts, services, repositories
authservice.sonar.tests=.
authservice.sonar.test.inclusions=**/*.test.ts
authservice.sonar.exclusions=**/*.test.ts
authservice.sonar.javascript.lcov.reportPaths=coverage/lcov.info

# --- Gateway Service ---
gatewayservice.sonar.projectName=Gateway Service
gatewayservice.sonar.sources=gatewayservice.ts, middleware.ts
gatewayservice.sonar.tests=.
gatewayservice.sonar.test.inclusions=**/*.test.ts
gatewayservice.sonar.exclusions=**/*.test.ts
gatewayservice.sonar.javascript.lcov.reportPaths=coverage/lcov.info

# --- Notification Service ---
notificationservice.sonar.projectName=Notification Service
notificationservice.sonar.sources=notificationservice.ts, validate.ts, services, repositories
notificationservice.sonar.tests=.
notificationservice.sonar.test.inclusions=**/*.test.ts
notificationservice.sonar.exclusions=**/*.test.ts
notificationservice.sonar.javascript.lcov.reportPaths=coverage/lcov.info
    
# --- Project Service ---
projectservice.sonar.projectName=Project Service
projectservice.sonar.sources=projectservice.ts, validate.ts, services, repositories
projectservice.sonar.tests=.
projectservice.sonar.test.inclusions=**/*.test.ts
projectservice.sonar.exclusions=**/*.test.ts
projectservice.sonar.javascript.lcov.reportPaths=coverage/lcov.info

# --- User Service ---
userservice.sonar.projectName=User Service
userservice.sonar.sources=userservice.ts, validate.ts, services, repositories
userservice.sonar.tests=.
userservice.sonar.test.inclusions=**/*.test.ts
userservice.sonar.exclusions=**/*.test.ts
userservice.sonar.javascript.lcov.reportPaths=coverage/lcov.info

# --- Web App ---
webapp.sonar.projectName=Web App
webapp.sonar.sources=src
webapp.sonar.tests=src
webapp.sonar.test.inclusions=src/**/*.test.ts, src/**/*.test.tsx, src/**/*.spec.ts, src/**/*.spec.tsx
webapp.sonar.exclusions=src/**/*.test.ts, src/**/*.test.tsx, src/**/*.spec.ts, src/**/*.spec.tsx
webapp.sonar.javascript.lcov.reportPaths=coverage/lcov.info