sonar.host.url=https://sonarcloud.io
sonar.organization=rolitoansu
sonar.projectKey=Rolitoansu_Match-TFE

sonar.modules=authservice,gatewayservice,notificationservice,projectservice,userservice,webapp

authservice.sonar.projectName=Auth Service
authservice.sonar.sources=authservice/authservice.ts, authservice/validate.ts, authservice/services, authservice/repositories
authservice.sonar.exclusions=authservice/**/*.test.ts
authservice.sonar.tests=authservice
authservice.sonar.javascript.lcov.reportPaths=authservice/coverage/lcov.info

gatewayservice.sonar.projectName=Gateway Service
gatewayservice.sonar.sources=gatewayservice/gatewayservice.ts, gatewayservice/middleware.ts
gatewayservice.sonar.exclusions=gatewayservice/**/*.test.ts
gatewayservice.sonar.tests=gatewayservice
gatewayservice.sonar.javascript.lcov.reportPaths=gatewayservice/coverage/lcov.info

notificationservice.sonar.projectName=Notification Service
notificationservice.sonar.sources=notificationservice/notificationservice.ts, notificationservice/validate.ts, notificationservice/services, notificationservice/repositories
notificationservice.sonar.exclusions=notificationservice/**/*.test.ts
notificationservice.sonar.tests=notificationservice
notificationservice.sonar.javascript.lcov.reportPaths=notificationservice/coverage/lcov.info
    
projectservice.sonar.projectName=Project Service
projectservice.sonar.sources=projectservice/projectservice.ts, projectservice/middleware.ts projectservice/services, projectservice/repositories
projectservice.sonar.exclusions=projectservice/**/*.test.ts
projectservice.sonar.tests=projectservice
projectservice.sonar.javascript.lcov.reportPaths=projectservice/coverage/lcov.info

userservice.sonar.projectName=User Service
userservice.sonar.sources=userservice/userservice.ts, userservice/middleware.ts userservice/services, userservice/repositories
userservice.sonar.exclusions=userservice/**/*.test.ts
userservice.sonar.tests=userservice
userservice.sonar.javascript.lcov.reportPaths=userservice/coverage/lcov.info

webapp.sonar.projectName=Web App
webapp.sonar.sources=webapp/src
webapp.sonar.exclusions=webapp/src/**/*.test.ts, webapp/src/**/*.spec.ts
webapp.sonar.tests=webapp/src
webapp.sonar.javascript.lcov.reportPaths=webapp/coverage/lcov.info